using System.Globalization;

namespace PredictiveAnalysis.Models;

/// <summary>
/// Per-machine analysis result shown on the dashboard. Blends the RulesEngine score,
/// the ML.NET probability, and (optionally) a Semantic Kernel generated recommendation.
/// </summary>
public sealed class MachineRiskItem
{
    public int Code { get; init; }
    public string MachineName { get; init; } = string.Empty;
    public string CostCenter { get; init; } = string.Empty;
    public string LastMaintDate { get; init; } = string.Empty;
    public int MaintenanceIntervalDays { get; init; }
    public int DaysSinceLastMaintenance { get; init; }
    public int TicketCount { get; init; }
    public double AvgDowntimeHours { get; init; }
    public int HighDowntimePartsCount { get; init; }
    public double OverallScore { get; set; }
    public double RuleScore { get; init; }
    public double MlRiskProbability { get; init; }
    public double OverallRiskScore { get; init; }
    public string Severity { get; init; } = string.Empty;
    public string Recommendation { get; set; } = string.Empty;

    /// <summary>Discrete risk flags raised by the RulesEngine (e.g. "Overdue", "High downtime").</summary>
    public List<string> RiskFactors { get; init; } = [];

    /// <summary>Most frequent problem reported in this machine's tickets.</summary>
    public string TopProblem { get; init; } = string.Empty;

    /// <summary>Days remaining until the next scheduled maintenance; negative when overdue.</summary>
    public int DaysUntilNextMaintenance => MaintenanceIntervalDays - DaysSinceLastMaintenance;

    /// <summary>Calendar date the next maintenance is due, derived from LastMaintDate + MaintenanceIntervalDays.</summary>
    public string NextMaintenanceDate => DateHelper.AddDays(LastMaintDate, MaintenanceIntervalDays);
}

public sealed class DashboardSummary
{
    public int TotalMachines { get; init; }
    public int CriticalMachines { get; init; }
    public int HighRiskMachines { get; init; }
    public double AvgRiskScore { get; init; }
    public List<MachineRiskItem> Machines { get; init; } = [];

    /// <summary>Overall fleet-health narrative generated by Semantic Kernel.</summary>
    public string FleetSummary { get; set; } = string.Empty;
}

/// <summary>Feature vector fed to the RulesEngine and the ML.NET model.</summary>
public sealed class MachineRiskInput
{
    public float DaysSinceLastMaintenance { get; set; }
    public float MaintenanceIntervalDays { get; set; }
    public float TicketCount { get; set; }
    public float AvgDowntimeHours { get; set; }
    public float HighDowntimePartsCount { get; set; }
}

public sealed class MachineRiskPrediction
{
    public bool PredictedLabel { get; set; }
    public float Probability { get; set; }
    public float Score { get; set; }
}

public static class DateHelper
{
    private static readonly string[] Formats = ["M/d/yyyy", "MM/dd/yyyy", "yyyy-MM-dd"];

    public static int CalculateDaysSince(string inputDate) =>
        TryParse(inputDate, out var parsedDate) ? (DateTime.Today - parsedDate).Days : 0;

    public static DateTime? ParseOrNull(string inputDate) =>
        TryParse(inputDate, out var parsedDate) ? parsedDate : null;

    /// <summary>Adds <paramref name="days"/> to <paramref name="inputDate"/>, returning it in the same "M/d/yyyy" style used throughout the mock data.</summary>
    public static string AddDays(string inputDate, int days) =>
        TryParse(inputDate, out var parsedDate) ? parsedDate.AddDays(days).ToString("M/d/yyyy", CultureInfo.InvariantCulture) : string.Empty;

    private static bool TryParse(string inputDate, out DateTime parsedDate)
    {
        if (!string.IsNullOrWhiteSpace(inputDate) &&
            (DateTime.TryParseExact(inputDate, Formats, CultureInfo.InvariantCulture, DateTimeStyles.None, out parsedDate) ||
             DateTime.TryParse(inputDate, CultureInfo.InvariantCulture, DateTimeStyles.None, out parsedDate)))
        {
            return true;
        }

        parsedDate = default;
        return false;
    }
}
